# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SolarX' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SolarX
  pod 'SVProgressHUD'
  pod 'SkyFloatingLabelTextField', '~> 3.0'
  pod 'TweeTextField'
  pod 'SKCountryPicker'
  pod 'CDAlertView'
  pod 'SwiftValidator', :git => 'https://github.com/jpotts18/SwiftValidator.git', :tag => '4.2.0'
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'RevealingSplashView'
  pod 'SwiftyJSON', '~> 4.0'
  pod 'MBAutoGrowingTextView', '~> 0.1.0'
  pod 'RSKGrowingTextView'
  pod 'NVActivityIndicatorView'
  pod 'Firebase/Storage'
  pod 'MIBlurPopup'
  pod 'Alamofire'
  pod 'MessageKit'
  pod 'Kingfisher'
  pod 'Firebase/Firestore'
  pod 'JSQMessagesViewController'
  pod "SAConfettiView"


end
